version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t hello:latest .
      - docker tag hello:latest 713290919116.dkr.ecr.us-east-1.amazonaws.com/hello      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 713290919116.dkr.ecr.us-east-1.amazonaws.com/hello
